file_format: "1"
id: apollo_macropad
name: Apollo_MacroPad
type: shield
requires:
  - pro_micro
features:
  - keys
  - studio
siblings:
  - apollo_macropad
boards:
  - nice_nano_v2
  - nice_nano
  - pro_micro
